# -*- coding: utf-8 -*-
"""PhishingAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfiLzjsNTunEjfShOi7m1U9hzsVSsY3b
"""

class PhishingAnalyzer:
    def __init__(self, email):
        self.email = email
        self.urgent_phrases = ["urgent", "immediate attention required", "overdue invoice",  "act now", "24 hours", "suspended", "final notice"]
        self.substitutions = {"1": "l", "0": "o", "3": "e", "5": "s", "@": "a"}
        self.known_brands = {
            "microsoft": "microsoft.com",
            "linkedin": "linkedin.com",
            "google": "google.com",
            "apple": "apple.com",
            "amazon": "amazon.com",
            "chatgpt": "openai.com",
            "paypal": "paypal.com",
            "netflix": "netflix.com",
            "facebook": "facebook.com",
        }

    def extract_domain(self):
      lines = self.email.split("\n")
      for line in lines:
        if line.startswith("From:"):
            from_line = line
      from_domain = from_line.split("@")[1].strip(">")
      self.from_domain = from_domain


def check_domain(self):
  self.extract_domain()
  lines = self.email.split("\n")
  for line in lines:
    if line.startswith("Reply-To:"):
      reply_to_line = line
  reply_to_domain = reply_to_line.split("@")[1]
  if self.from_domain != reply_to_domain:
    print(f"⚠️ ALERT! From Domain: '{self.from_domain}' and the Reply To Domain: '{reply_to_domain}' do not match!")
  else:
    print(f'✅ Domains match: {self.from_domain}')

def check_urgency(self):
  matching_list = []
  for phrase in self.urgent_phrases:
    if phrase in self.email.lower():
      matching_list.append(phrase)
  return matching_list

def normalize_domain(self):
    self.extract_domain()
    normalized = self.from_domain
    for fake_char, real_char in self.substitutions.items():
        normalized = normalized.replace(fake_char, real_char)
    self.normalized_domain = normalized

def check_lookalike(self):
  match = []
  self.normalize_domain()

  for brand_name, real_domain in self.known_brands.items():
        if brand_name in self.normalized_domain and self.from_domain != real_domain:
            match.append((brand_name, real_domain))

  if not match:
    print("✅ No lookalike brands detected.")
  else:
    print("⚠️ Lookalike brands detected:")
    for brand_name, real_domain in match:
      print(f"Brand: {brand_name}, Real Domain: {real_domain}")

