# -*- coding: utf-8 -*-
"""PhishingAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfiLzjsNTunEjfShOi7m1U9hzsVSsY3b
"""

import anthropic
import os
from google.colab import userdata
# Note: userdata.get() is Colab-specific and requires the key to be stored in
# Colab's Secrets manager. This line will not run outside a Colab notebook
api_key = userdata.get('ANTHROPIC_API_KEY')
client = anthropic.Anthropic(api_key=api_key)

class ReportGenerator:
    def __init__(self, client):
        self.client = client

    def generate_summary(self, domain_result, urgency_result, lookalike_result):
        prompt_text = f"""
        Here is phishing analyzer data:
        Domain check: {domain_result}
        Urgent phrases found: {urgency_result}
        Lookalike brands: {lookalike_result}

        Summarize this as a short phishing analysis report in one paragraph.
        """
        message = self.client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=300,
            messages=[
                {"role": "user", "content": prompt_text}
            ]
        )
        print("\n")
        return message.content[0].text

class PhishingAnalyzer:
    def __init__(self, email_path):
      self.email_path = email_path
      with open(self.email_path) as file:
        self.email = file.read()

      self.urgent_phrases = ["urgent", "immediate attention required", "overdue invoice",
                                "act now", "24 hours", "suspended", "final notice"]
      self.substitutions = {"1": "l", "0": "o", "3": "e", "5": "s", "@": "a"}
      self.known_brands = {
            "microsoft": "microsoft.com",
            "linkedin": "linkedin.com",
            "google": "google.com",
            "apple": "apple.com",
            "amazon": "amazon.com",
            "chatgpt": "openai.com",
            "paypal": "paypal.com",
            "netflix": "netflix.com",
            "facebook": "facebook.com",
        }

    def extract_domain(self):
        lines = self.email.split("\n")
        for line in lines:
            if line.startswith("From:"):
                from_line = line
        self.from_domain = from_line.split("@")[1].strip(">")

    def check_domain(self):
        self.extract_domain()
        lines = self.email.split("\n")
        for line in lines:
            if line.startswith("Reply-To:"):
                reply_to_line = line
        reply_to_domain = reply_to_line.split("@")[1]
        if self.from_domain != reply_to_domain:
            message_alert = f"⚠️ ALERT! From Domain: '{self.from_domain}' and the Reply To Domain: '{reply_to_domain}' do not match!"
            print(message_alert)
            return message_alert
        else:
            message_pass = f"✅ Domains match: {self.from_domain}"
            print(message_pass)
            return message_pass

    def check_urgency(self):
        matching_list = []
        for phrase in self.urgent_phrases:
            if phrase in self.email.lower():
                matching_list.append(phrase)
        return matching_list

    def normalize_domain(self):
        self.extract_domain()
        normalized = self.from_domain
        for fake_char, real_char in self.substitutions.items():
            normalized = normalized.replace(fake_char, real_char)
        self.normalized_domain = normalized

    def check_lookalike(self):
        match = []
        self.normalize_domain()
        for brand_name, real_domain in self.known_brands.items():
            if brand_name in self.normalized_domain and self.from_domain != real_domain:
                match.append((brand_name, real_domain))

        messages = []
        if not match:
            message = "✅ No lookalike brands detected."
            print(message)
            messages.append(message)
        else:
            print("⚠️ Lookalike brands detected:")
            for brand_name, real_domain in match:
                message = f"Brand: {brand_name}, Real Domain: {real_domain}"
                print(message)
                messages.append(message)
        return messages

class BatchProcessor:
    def __init__(self, client):
        self.client = client
    def process_email_folder(self, folder):
      for filename in os.listdir(folder):
          print(f"--- {filename} ---")
          full_path = os.path.join(folder, filename)
          analyzer = PhishingAnalyzer(full_path)
          domain_result = analyzer.check_domain()
          urgency_result = analyzer.check_urgency()
          lookalike_result = analyzer.check_lookalike()
          if domain_result.startswith("⚠️") or urgency_result or not("✅ No lookalike brands detected." in lookalike_result):
            report_generator = ReportGenerator(self.client)
            report = report_generator.generate_summary(domain_result, urgency_result, lookalike_result)
            print(report)
          else: print("✅ Clean, no AI summary needed")
          print("\n")

batch_processor = BatchProcessor(client)
batch_processor.process_email_folder("Emails")

!pip install anthropic

